server:
  port: 8000

spring:
  profiles:
    active: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        sql: debug
        type: trace